---

# Deploy Common Configuration to indexer cluster master

- block:
  - name: "Deploy Indexer common configuration to indexer cluster master"
    copy: src={{ platform_repos_home }}/{{ env_dir }}/indexer/{{ item }} dest={{ splunk_etc }}/slave-apps
    with_items:
      - idx_common_config